CREATE DATABASE SUPERVALIDO;

USE SUPERVALIDO;

CREATE TABLE ESTADO (
  EST_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  EST_STR_DESCRICAO VARCHAR(80)   NOT NULL ,
  EST_STR_SIGLA CHAR(2),
PRIMARY KEY(EST_INT_ID));

CREATE TABLE PROMOCAO (
  PRO_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  PRO_STR_DESCRICAO VARCHAR(80)   NOT NULL ,
  PRO_DAT_DATAINICIO DATE   NOT NULL ,
  PRO_DAT_DATAEXPIRACAO DATE   NOT NULL   ,
PRIMARY KEY(PRO_INT_ID));

CREATE TABLE MARCA (
  MAR_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  MAR_STR_DESCRICAO VARCHAR(120)   NOT NULL   ,
PRIMARY KEY(MAR_INT_ID));

CREATE TABLE OFERTAEXCLUSIVA (
  OFE_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  OFE_STR_DESCRICAO VARCHAR(80)   NOT NULL ,
  OFE_INT_PONTUACAODESCONTO INTEGER   NOT NULL ,
  OFE_DAT_DATAINICIO DATE   NOT NULL ,
  OFE_DAT_DATAEXPIRACAO DATE   NOT NULL   ,
PRIMARY KEY(OFE_INT_ID));

CREATE TABLE CATEGORIA (
  CAT_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  CAT_STR_DESCRICAO VARCHAR(80)   NOT NULL   ,
PRIMARY KEY(CAT_INT_ID));

CREATE TABLE NOTIFICACAO (
  NOT_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  PRO_INT_ID INTEGER   NOT NULL ,
  NOT_STR_DESCRICAO VARCHAR(80)   NOT NULL,
PRIMARY KEY(NOT_INT_ID, PRO_INT_ID),
FOREIGN KEY(PRO_INT_ID) REFERENCES PROMOCAO(PRO_INT_ID));

CREATE INDEX FK_NOTIFICACAO ON NOTIFICACAO (PRO_INT_ID);

CREATE TABLE CIDADE (
  CID_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  EST_INT_ID INTEGER   NOT NULL ,
  CID_STR_DESCRICAO VARCHAR(100)   NOT NULL   ,
PRIMARY KEY(CID_INT_ID)  ,
FOREIGN KEY(EST_INT_ID) REFERENCES ESTADO(EST_INT_ID));

CREATE INDEX FK_CIDADE ON CIDADE (EST_INT_ID);

CREATE TABLE ENDERECO (
  END_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  CID_INT_ID INTEGER   NOT NULL ,
  END_STR_LOGRADOURO VARCHAR(80)   NOT NULL ,
  END_STR_NUMERO VARCHAR(10)   NOT NULL ,
  END_STR_BAIRRO VARCHAR(50)   NOT NULL ,
  END_STR_CEP CHAR(8)   NOT NULL   ,
PRIMARY KEY(END_INT_ID)  ,
FOREIGN KEY(CID_INT_ID) REFERENCES CIDADE(CID_INT_ID));

CREATE INDEX FK_ENDERECO ON ENDERECO (CID_INT_ID);

CREATE TABLE SUPERMERCADO (
  SUP_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  END_INT_ID INTEGER   NOT NULL ,
  SUP_STR_NOMEFANTASIA VARCHAR(80)   NOT NULL ,
  SUP_STR_RAZAOSOCIAL VARCHAR(200)    ,
  SUP_STR_CNPJ CHAR(14)    ,
  SUP_STR_NOMEREPRESENTANTE VARCHAR(50)    ,
  SUP_STR_TELEFONE CHAR(11)    ,
  SUP_STR_EMAIL VARCHAR(120)    ,
  SUP_STR_SITE VARCHAR(200)      ,
PRIMARY KEY(SUP_INT_ID)    ,
FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID));


CREATE INDEX FK_SUPERMERCADO_END ON SUPERMERCADO (END_INT_ID);
CREATE INDEX UK_SUPERMERCADO ON SUPERMERCADO (SUP_STR_CNPJ, SUP_STR_TELEFONE, SUP_STR_EMAIL, SUP_STR_SITE);


CREATE TABLE USUARIO (
  USU_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  END_INT_ID INTEGER   NOT NULL ,
  USU_STR_DESCRICAO VARCHAR(80)   NOT NULL ,
  USU_STR_TELEFONE CHAR(11)   NOT NULL ,
  USU_STR_EMAIL VARCHAR(120)   NOT NULL   ,
PRIMARY KEY(USU_INT_ID)    ,
FOREIGN KEY(END_INT_ID) REFERENCES ENDERECO(END_INT_ID));

CREATE INDEX FK_USUARIO_END ON USUARIO (END_INT_ID);
CREATE INDEX UK_USUARIO ON USUARIO (USU_STR_TELEFONE, USU_STR_EMAIL);

CREATE TABLE LISTAPREFERENCIA (
  LIS_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  USU_INT_ID INTEGER   NOT NULL ,
  LIS_STR_DESCRICAO VARCHAR(80)   NOT NULL   ,
PRIMARY KEY(LIS_INT_ID)  ,
FOREIGN KEY(USU_INT_ID) REFERENCES USUARIO(USU_INT_ID));

CREATE INDEX FK_PREFERENCIAPRODUTO_USU ON LISTAPREFERENCIA (USU_INT_ID);

CREATE TABLE INSTITUICAOONG (
  ONG_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  USU_INT_ID INTEGER   NOT NULL ,
  ONG_STR_TELEFONE CHAR(11)   NOT NULL ,
  ONG_STR_RAZAOSOCIAL VARCHAR(200)   NOT NULL ,
  ONG_STR_CNPJ CHAR(14)   NOT NULL ,
  ONG_STR_NOMEREPRESENTANTE VARCHAR(50)   NOT NULL ,
  ONG_STR_SITE VARCHAR(200)   NOT NULL   ,
PRIMARY KEY(ONG_INT_ID, USU_INT_ID)    ,
FOREIGN KEY(USU_INT_ID) REFERENCES USUARIO(USU_INT_ID));

CREATE INDEX FK_INSTITUICAOONG_USU ON INSTITUICAOONG (USU_INT_ID);
CREATE INDEX UK_INSTITUICAOONG ON INSTITUICAOONG (ONG_STR_SITE, ONG_STR_CNPJ, ONG_STR_TELEFONE);

CREATE TABLE AVALIACAOEXPERIENCIA (
  AVA_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  SUP_INT_ID INTEGER   NOT NULL ,
  USU_INT_ID INTEGER   NOT NULL ,
  AVA_STR_DESCRICAO VARCHAR(200)   NOT NULL   ,
PRIMARY KEY(AVA_INT_ID)    ,
FOREIGN KEY(USU_INT_ID) REFERENCES USUARIO(USU_INT_ID),
FOREIGN KEY(SUP_INT_ID) REFERENCES SUPERMERCADO(SUP_INT_ID));

CREATE INDEX FK_AVALIACAOEXPERIENCIA_USU ON AVALIACAOEXPERIENCIA (USU_INT_ID);
CREATE INDEX FK_AVALIACAOEXPERIENCIA_SUP ON AVALIACAOEXPERIENCIA (SUP_INT_ID);

CREATE TABLE MERCADOLISTAPREFERENCIA (
  MEL_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  LIS_INT_ID INTEGER   NOT NULL ,
  SUP_INT_ID INTEGER   NOT NULL   ,
PRIMARY KEY(MEL_INT_ID)    ,
FOREIGN KEY(LIS_INT_ID)REFERENCES LISTAPREFERENCIA(LIS_INT_ID),
FOREIGN KEY(SUP_INT_ID)REFERENCES SUPERMERCADO(SUP_INT_ID));

CREATE INDEX FK_MERCADOLISTAPREFERENCIA_LIS ON MERCADOLISTAPREFERENCIA (LIS_INT_ID);
CREATE INDEX FK_MERCADOLISTAPREFERENCIA_SUP ON MERCADOLISTAPREFERENCIA (SUP_INT_ID);

CREATE TABLE USUARIONOTIFICACAO (
  USN_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  USU_INT_ID INTEGER   NOT NULL ,
  PRO_INT_ID INTEGER   NOT NULL ,
  NOT_INT_ID INTEGER   NOT NULL ,
  USN_STR_DESCRICAO VARCHAR(80)   NOT NULL   ,
PRIMARY KEY(USN_INT_ID)    ,
FOREIGN KEY(USU_INT_ID) REFERENCES USUARIO(USU_INT_ID),
FOREIGN KEY(NOT_INT_ID, PRO_INT_ID) REFERENCES NOTIFICACAO(NOT_INT_ID, PRO_INT_ID));

CREATE INDEX FK_USUARIONOTIFICACAO_USU ON USUARIONOTIFICACAO (USU_INT_ID);
CREATE INDEX FK_USUARIONOTIFICACAO_NOT ON USUARIONOTIFICACAO (NOT_INT_ID, PRO_INT_ID);


CREATE TABLE PRODUTO (
  PRO_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  SUP_INT_ID INTEGER   NOT NULL ,
  OFE_INT_ID INTEGER   NOT NULL ,
  CAT_INT_ID INTEGER   NOT NULL ,
  MAR_INT_ID INTEGER   NOT NULL ,
  PRO_STR_DESCRICAO VARCHAR(120)   NOT NULL ,
  PRO_DAT_DATAVENCIMENTO DATE   NOT NULL ,
  PRO_DOU_PRECO FLOAT   NOT NULL ,
  PRO_INT_QUANTIDADE INTEGER   NOT NULL   ,
PRIMARY KEY(PRO_INT_ID)        ,
FOREIGN KEY(CAT_INT_ID) REFERENCES CATEGORIA(CAT_INT_ID),
FOREIGN KEY(MAR_INT_ID) REFERENCES MARCA(MAR_INT_ID),
FOREIGN KEY(SUP_INT_ID) REFERENCES SUPERMERCADO(SUP_INT_ID),
FOREIGN KEY(OFE_INT_ID) REFERENCES OFERTAEXCLUSIVA(OFE_INT_ID));

CREATE INDEX FK_PRODUTO_CAT ON PRODUTO (CAT_INT_ID);
CREATE INDEX FK_PRODUTO_MAR ON PRODUTO (MAR_INT_ID);
CREATE INDEX FK_PRODUTO_SUP ON PRODUTO (SUP_INT_ID);
CREATE INDEX FK_PRODUTO_OFE ON PRODUTO (OFE_INT_ID);

CREATE TABLE USUARIOCOMUM (
  USC_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  USU_INT_ID INTEGER   NOT NULL ,
  USC_STR_CPF CHAR(11)   NOT NULL ,
  USC_STR_TELCELULAR CHAR(11)   NOT NULL   ,
PRIMARY KEY(USC_INT_ID, USU_INT_ID)    ,
FOREIGN KEY(USU_INT_ID) REFERENCES USUARIO(USU_INT_ID));

CREATE INDEX FK_USUARIOCOMUM_USU ON USUARIOCOMUM (USU_INT_ID);
CREATE INDEX UK_USUARIOCOMUM ON USUARIOCOMUM (USC_STR_CPF, USC_STR_TELCELULAR);


CREATE TABLE PONTUACAOUSUARIO (
  PON_INT_ID INTEGER   NOT NULL IDENTITY(1,1),
  USU_INT_ID INTEGER   NOT NULL ,
  PON_INT_PONTO INTEGER      ,
PRIMARY KEY(PON_INT_ID)  ,
FOREIGN KEY(USU_INT_ID) REFERENCES USUARIO(USU_INT_ID));

CREATE INDEX FK_PONTUACAOUSUARIO_USU ON PONTUACAOUSUARIO (USU_INT_ID);

CREATE TABLE PRODUTOLISTAPREFERENCIA (
  PRL_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  PRO_INT_ID INTEGER NOT NULL,
  LIS_INT_ID INTEGER NOT NULL,
PRIMARY KEY(PRL_INT_ID),
FOREIGN KEY(LIS_INT_ID) REFERENCES LISTAPREFERENCIA(LIS_INT_ID),
FOREIGN KEY(PRO_INT_ID) REFERENCES PRODUTO(PRO_INT_ID));


CREATE INDEX FK_PRODUTOLISTAPREFERENCIA_LIS ON PRODUTOLISTAPREFERENCIA (LIS_INT_ID);
CREATE INDEX FK_PRODUTOLISTAPREFERENCIA_PRO ON PRODUTOLISTAPREFERENCIA (PRO_INT_ID);


CREATE TABLE NOTAFISCAL (
  NFI_INT_ID INTEGER NOT NULL IDENTITY(1,1),
  PON_INT_ID INTEGER NOT NULL ,
  SUP_INT_ID INTEGER NOT NULL ,
  USU_INT_ID INTEGER NOT NULL ,
  NFI_STR_NUMERO CHAR(9) NOT NULL ,
  NFI_STR_DESCRICAO VARCHAR(80) NOT NULL ,
PRIMARY KEY(NFI_INT_ID),
FOREIGN KEY(SUP_INT_ID) REFERENCES SUPERMERCADO(SUP_INT_ID),
FOREIGN KEY(USU_INT_ID) REFERENCES USUARIO(USU_INT_ID),
FOREIGN KEY(PON_INT_ID) REFERENCES PONTUACAOUSUARIO(PON_INT_ID));

CREATE INDEX FK_NOTAFISCAL_SUP ON NOTAFISCAL (SUP_INT_ID);
CREATE INDEX FK_NOTAFISCAL_USU ON NOTAFISCAL (USU_INT_ID);
CREATE INDEX FK_NOTAFISCAL_PON ON NOTAFISCAL (PON_INT_ID);
CREATE INDEX UK_NOTAFISCAL ON NOTAFISCAL (NFI_STR_NUMERO);

