USE SUPERVALIDO;

--  informações sobre os supermercados com seus respectivos endereços
CREATE VIEW vw_SUPERMERCADOSENDERECOS AS
SELECT 
	s.SUP_INT_ID AS ID_DO_SUPERMERCADO,
    s.SUP_STR_NOMEFANTASIA AS SUPERMERCADO,
    s.SUP_STR_RAZAOSOCIAL AS RAZAO_SOCIAL,
    s.SUP_STR_CNPJ AS CNPJ,
    s.SUP_STR_NOMEREPRESENTANTE AS REPRESENTANTE,
    s.SUP_STR_TELEFONE AS TELEFONE,
    s.SUP_STR_EMAIL AS EMAIL,
    s.SUP_STR_SITE AS SITE,
    e.END_STR_LOGRADOURO AS LOGRADOURO,
    e.END_STR_NUMERO AS NUMERO,
    e.END_STR_BAIRRO AS BAIRRO,
    e.END_STR_CEP AS CEP,
    c.CID_STR_DESCRICAO AS CIDADE,
    es.EST_STR_DESCRICAO AS ESTADO,
    es.EST_STR_SIGLA AS SGLA
FROM SUPERMERCADO s
JOIN ENDERECO e ON s.END_INT_ID = e.END_INT_ID
JOIN CIDADE c ON e.CID_INT_ID = c.CID_INT_ID
JOIN ESTADO es ON c.EST_INT_ID = es.EST_INT_ID;

-- dados dos produtos com informações de suas categorias, marcas, supermercados e ofertas exclusivas
CREATE VIEW vw_PRODUTOSCOMPLETOS AS
SELECT
	p.PRO_INT_ID AS ID_DO_PRODUTO,
    p.PRO_STR_DESCRICAO AS PRODUTO,
    p.PRO_DAT_DATAVENCIMENTO AS DATA_DE_VENCIMENTO ,
    p.PRO_DOU_PRECO AS PREÇO,
    p.PRO_INT_QUANTIDADE AS QUANTIDADE,
    c.CAT_STR_DESCRICAO AS CATEGORIA,
    m.MAR_STR_DESCRICAO AS MARCA,
    s.SUP_STR_NOMEFANTASIA AS SUPERMERCADO,
    o.OFE_STR_DESCRICAO AS OFERTA,
    o.OFE_INT_PONTUACAODESCONTO AS PONTOS_DE_DESCONTO,
    o.OFE_DAT_DATAINICIO AS INICIO_DE_DESCONTO,
    o.OFE_DAT_DATAEXPIRACAO AS EXPIRACAO_DE_DESCONTO
FROM PRODUTO p
JOIN CATEGORIA c ON p.CAT_INT_ID = c.CAT_INT_ID
JOIN MARCA m ON p.MAR_INT_ID = m.MAR_INT_ID
JOIN SUPERMERCADO s ON p.SUP_INT_ID = s.SUP_INT_ID
JOIN OFERTAEXCLUSIVA o ON p.OFE_INT_ID = o.OFE_INT_ID;

-- informações dos usuários com suas respectivas pontuações
CREATE VIEW vw_USUARIOSPONTUACOES AS
SELECT
    u.USU_INT_ID AS ID_DO_USUARIO,
    u.USU_STR_DESCRICAO AS NOME,
    u.USU_STR_TELEFONE AS TELEFONE,
    u.USU_STR_EMAIL AS EMAIL,
    p.PON_INT_PONTO AS PONTUAÇÃO
FROM USUARIO u
LEFT JOIN PONTUACAOUSUARIO p ON u.USU_INT_ID = p.USU_INT_ID;

-- informações sobre as notificações de promoções enviadas para os usuários
CREATE VIEW vw_NOTIFICACOESPROMOCOES AS
SELECT
    un.USN_INT_ID AS ID,
    u.USU_STR_DESCRICAO AS USUARIO,
    n.NOT_STR_DESCRICAO AS NOTIFICACAO,
    p.PRO_STR_DESCRICAO AS PROMOCAO,
	un.USN_STR_DESCRICAO AS DESCRICAO_DA_NOTIFICACAO
FROM USUARIONOTIFICACAO un
JOIN USUARIO u ON un.USU_INT_ID = u.USU_INT_ID
JOIN NOTIFICACAO n ON un.NOT_INT_ID = n.NOT_INT_ID AND un.PRO_INT_ID = n.PRO_INT_ID
JOIN PROMOCAO p ON n.PRO_INT_ID = p.PRO_INT_ID;

-- avaliações de usuários sobre suas experiências (de compra) nos supermercados
CREATE VIEW vw_AVALIACOESEXPERIENCIAS AS
SELECT
	ae.AVA_INT_ID AS ID_DA_AVALIACAO,
    u.USU_STR_DESCRICAO AS USUARIO,
    s.SUP_STR_NOMEFANTASIA AS SUPERMERCADO,
    ae.AVA_STR_DESCRICAO AS AVALIACAO
FROM AVALIACAOEXPERIENCIA ae
JOIN USUARIO u ON ae.USU_INT_ID = u.USU_INT_ID
JOIN SUPERMERCADO s ON ae.SUP_INT_ID = s.SUP_INT_ID;


